apiVersion: v1
kind: ServiceAccount
metadata:
  name: powercap-manager
  namespace: default
  labels:
    app.kubernetes.io/name: powercap-manager
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: power-management

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: powercap-manager
  labels:
    app.kubernetes.io/name: powercap-manager
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: power-management
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: powercap-manager
  labels:
    app.kubernetes.io/name: powercap-manager
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: power-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: powercap-manager
subjects:
- kind: ServiceAccount
  name: powercap-manager
  namespace: default